-- ORIGINS DATA FOUNDATION V1
-- PostgreSQL schema inspired by Zircon's DBObjects/associations while keeping
-- content definitions separate from persistent player/runtime state.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS content;
CREATE SCHEMA IF NOT EXISTS player;
CREATE SCHEMA IF NOT EXISTS gameplay;

-- -----------------------------------------------------------------------------
-- CONTENT: definitions shared by every player/server instance
-- -----------------------------------------------------------------------------

CREATE TABLE content.class_definitions (
    id              smallint PRIMARY KEY,
    code            varchar(32) NOT NULL UNIQUE,
    display_name    varchar(64) NOT NULL,
    source_system   varchar(32),
    source_repo     text,
    source_path     text,
    source_commit   varchar(64),
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE content.map_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(128) NOT NULL UNIQUE,
    display_name        varchar(128) NOT NULL,
    theme_key           varchar(128),
    source_system       varchar(32),
    source_numeric_id   integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX map_definitions_source_uidx
    ON content.map_definitions(source_system, source_numeric_id)
    WHERE source_system IS NOT NULL AND source_numeric_id IS NOT NULL;

CREATE TABLE content.magic_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(128) NOT NULL UNIQUE,
    name                varchar(128) NOT NULL,
    class_id            smallint NOT NULL REFERENCES content.class_definitions(id),
    source_system       varchar(32) NOT NULL,
    source_spell_id     integer,
    magic_type          varchar(128),
    school              varchar(64),
    property            varchar(64),
    element             varchar(32),
    icon_library        varchar(128),
    icon_index          integer,
    icon_frame_normal   integer,
    icon_frame_pressed  integer,
    min_base_power      integer,
    max_base_power      integer,
    min_level_power     integer,
    max_level_power     integer,
    base_cost           integer,
    level_cost          integer,
    need_level_1        integer,
    need_level_2        integer,
    need_level_3        integer,
    experience_1        bigint,
    experience_2        bigint,
    experience_3        bigint,
    delay_ms            integer,
    range_cells         integer,
    description         text,
    source_implemented  boolean NOT NULL DEFAULT true,
    source_issue        text,
    source_repo         text NOT NULL,
    source_path         text NOT NULL,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CHECK (need_level_1 IS NULL OR need_level_1 >= 0),
    CHECK (need_level_2 IS NULL OR need_level_2 >= 0),
    CHECK (need_level_3 IS NULL OR need_level_3 >= 0),
    CHECK (delay_ms IS NULL OR delay_ms >= 0)
);

CREATE UNIQUE INDEX magic_definitions_source_uidx
    ON content.magic_definitions(source_system, source_spell_id)
    WHERE source_spell_id IS NOT NULL;

CREATE TABLE content.item_definitions (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key                varchar(160) NOT NULL UNIQUE,
    item_name               varchar(160) NOT NULL,
    item_type               varchar(64) NOT NULL,
    required_class_mask     integer NOT NULL DEFAULT 0,
    required_gender         varchar(32),
    required_type           varchar(64),
    required_amount         integer,
    shape                   integer,
    item_effect             varchar(128),
    exterior_effect         varchar(128),
    image_library           varchar(128),
    image_index             integer,
    ground_library          varchar(128),
    ground_index            integer,
    durability              integer,
    price                   bigint,
    weight                  integer,
    stack_size              integer NOT NULL DEFAULT 1,
    start_item              boolean NOT NULL DEFAULT false,
    sell_rate               numeric(8,4) NOT NULL DEFAULT 0.5,
    can_repair              boolean NOT NULL DEFAULT true,
    can_sell                boolean NOT NULL DEFAULT true,
    can_store               boolean NOT NULL DEFAULT true,
    can_trade               boolean NOT NULL DEFAULT true,
    can_drop                boolean NOT NULL DEFAULT true,
    can_death_drop          boolean NOT NULL DEFAULT true,
    rarity                  varchar(64),
    buff_icon               integer,
    part_count              integer,
    description             text,
    source_system           varchar(32),
    source_item_id          integer,
    source_repo             text,
    source_path             text,
    source_commit           varchar(64),
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    CHECK (stack_size > 0),
    CHECK (durability IS NULL OR durability >= 0),
    CHECK (weight IS NULL OR weight >= 0)
);

CREATE UNIQUE INDEX item_definitions_source_uidx
    ON content.item_definitions(source_system, source_item_id)
    WHERE source_system IS NOT NULL AND source_item_id IS NOT NULL;

CREATE TABLE content.item_stats (
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    stat_code           varchar(64) NOT NULL,
    amount              integer NOT NULL,
    PRIMARY KEY (item_definition_id, stat_code)
);

CREATE TABLE content.monster_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(160) NOT NULL UNIQUE,
    monster_name        varchar(160) NOT NULL,
    image_library       varchar(128),
    image_index         integer,
    ai_code             integer,
    level               integer NOT NULL DEFAULT 1,
    view_range          integer NOT NULL DEFAULT 7,
    cool_eye            integer,
    experience          numeric(30,0) NOT NULL DEFAULT 0,
    undead              boolean NOT NULL DEFAULT false,
    can_push            boolean NOT NULL DEFAULT true,
    can_tame            boolean NOT NULL DEFAULT false,
    attack_delay_ms     integer NOT NULL DEFAULT 2500,
    move_delay_ms       integer NOT NULL DEFAULT 1800,
    is_boss             boolean NOT NULL DEFAULT false,
    monster_flag        varchar(128),
    face_image          integer,
    source_system       varchar(32),
    source_monster_id   integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    CHECK (level >= 0),
    CHECK (view_range >= 0),
    CHECK (attack_delay_ms >= 0),
    CHECK (move_delay_ms >= 0)
);

CREATE UNIQUE INDEX monster_definitions_source_uidx
    ON content.monster_definitions(source_system, source_monster_id)
    WHERE source_system IS NOT NULL AND source_monster_id IS NOT NULL;

CREATE TABLE content.monster_stats (
    monster_definition_id bigint NOT NULL REFERENCES content.monster_definitions(id) ON DELETE CASCADE,
    stat_code             varchar(64) NOT NULL,
    amount                integer NOT NULL,
    PRIMARY KEY (monster_definition_id, stat_code)
);

CREATE TABLE content.monster_drops (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monster_definition_id   bigint NOT NULL REFERENCES content.monster_definitions(id) ON DELETE CASCADE,
    item_definition_id      bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    chance                  numeric(12,8) NOT NULL,
    min_count               integer NOT NULL DEFAULT 1,
    max_count               integer NOT NULL DEFAULT 1,
    group_key               varchar(64),
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (chance >= 0 AND chance <= 1),
    CHECK (min_count > 0),
    CHECK (max_count >= min_count)
);

CREATE TABLE content.monster_respawns (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monster_definition_id   bigint NOT NULL REFERENCES content.monster_definitions(id) ON DELETE CASCADE,
    map_definition_id       bigint NOT NULL REFERENCES content.map_definitions(id) ON DELETE CASCADE,
    x                       integer NOT NULL,
    y                       integer NOT NULL,
    radius                  integer NOT NULL DEFAULT 0,
    spawn_count             integer NOT NULL DEFAULT 1,
    respawn_delay_ms        integer NOT NULL DEFAULT 60000,
    random_delay_ms         integer NOT NULL DEFAULT 0,
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (radius >= 0),
    CHECK (spawn_count > 0),
    CHECK (respawn_delay_ms >= 0),
    CHECK (random_delay_ms >= 0)
);

CREATE TABLE content.buff_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(128) NOT NULL UNIQUE,
    name                varchar(128) NOT NULL,
    buff_type           varchar(128),
    icon_library        varchar(128),
    icon_index          integer,
    description         text,
    source_system       varchar(32),
    source_numeric_id   integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE content.quest_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(160) NOT NULL UNIQUE,
    title               varchar(200) NOT NULL,
    description         text,
    required_level      integer,
    source_system       varchar(32),
    source_numeric_id   integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
);

-- -----------------------------------------------------------------------------
-- PLAYER: persistent account/character state (Zircon CharacterInfo/UserMagic style)
-- -----------------------------------------------------------------------------

CREATE TABLE player.accounts (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    account_name    varchar(64) NOT NULL UNIQUE,
    email           varchar(320),
    password_hash   text,
    status          varchar(32) NOT NULL DEFAULT 'active',
    created_at      timestamptz NOT NULL DEFAULT now(),
    last_login_at   timestamptz
);

CREATE UNIQUE INDEX accounts_email_uidx
    ON player.accounts(lower(email))
    WHERE email IS NOT NULL;

CREATE TABLE player.characters (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id          uuid NOT NULL REFERENCES player.accounts(id) ON DELETE CASCADE,
    character_name      varchar(64) NOT NULL UNIQUE,
    class_id            smallint NOT NULL REFERENCES content.class_definitions(id),
    gender              varchar(32),
    level               integer NOT NULL DEFAULT 1,
    experience          numeric(30,0) NOT NULL DEFAULT 0,
    hair_type           integer,
    hair_colour         integer,
    armour_colour       integer,
    current_hp          integer NOT NULL DEFAULT 1,
    current_mp          integer NOT NULL DEFAULT 0,
    current_map_id      bigint REFERENCES content.map_definitions(id),
    current_x           integer,
    current_y           integer,
    direction           smallint NOT NULL DEFAULT 0,
    bind_map_id         bigint REFERENCES content.map_definitions(id),
    bind_x              integer,
    bind_y              integer,
    attack_mode         varchar(32),
    pet_mode            varchar(32),
    pk_points           integer NOT NULL DEFAULT 0,
    observable          boolean NOT NULL DEFAULT true,
    deleted             boolean NOT NULL DEFAULT false,
    created_at          timestamptz NOT NULL DEFAULT now(),
    last_login_at       timestamptz,
    last_logout_at      timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (level >= 0),
    CHECK (current_hp >= 0),
    CHECK (current_mp >= 0)
);

CREATE INDEX characters_account_idx ON player.characters(account_id);
CREATE INDEX characters_class_idx ON player.characters(class_id);

CREATE TABLE player.character_magics (
    character_id        uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    magic_definition_id bigint NOT NULL REFERENCES content.magic_definitions(id) ON DELETE RESTRICT,
    level               integer NOT NULL DEFAULT 0,
    experience          bigint NOT NULL DEFAULT 0,
    set1_key            smallint,
    set2_key            smallint,
    set3_key            smallint,
    set4_key            smallint,
    item_required       boolean NOT NULL DEFAULT false,
    cooldown_until      timestamptz,
    learned_at          timestamptz NOT NULL DEFAULT now(),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (character_id, magic_definition_id),
    CHECK (level >= 0),
    CHECK (experience >= 0)
);

CREATE INDEX character_magics_magic_idx ON player.character_magics(magic_definition_id);

CREATE TABLE player.item_instances (
    id                      uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    item_definition_id      bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE RESTRICT,
    owner_character_id      uuid REFERENCES player.characters(id) ON DELETE SET NULL,
    count                   bigint NOT NULL DEFAULT 1,
    current_durability      integer,
    max_durability_override integer,
    bound                   boolean NOT NULL DEFAULT false,
    acquired_at             timestamptz NOT NULL DEFAULT now(),
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (count > 0),
    CHECK (current_durability IS NULL OR current_durability >= 0),
    CHECK (max_durability_override IS NULL OR max_durability_override >= 0)
);

CREATE INDEX item_instances_owner_idx ON player.item_instances(owner_character_id);
CREATE INDEX item_instances_definition_idx ON player.item_instances(item_definition_id);

CREATE TABLE player.character_item_slots (
    character_id        uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    slot_group          varchar(32) NOT NULL,
    slot_index          integer NOT NULL,
    item_instance_id    uuid NOT NULL UNIQUE REFERENCES player.item_instances(id) ON DELETE CASCADE,
    PRIMARY KEY (character_id, slot_group, slot_index),
    CHECK (slot_index >= 0),
    CHECK (slot_group IN ('inventory','equipment','belt','storage','quest','trade','refine'))
);

CREATE TABLE player.character_buffs (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    character_id        uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    buff_definition_id  bigint NOT NULL REFERENCES content.buff_definitions(id) ON DELETE RESTRICT,
    level               integer NOT NULL DEFAULT 1,
    stack_count         integer NOT NULL DEFAULT 1,
    expires_at          timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (level >= 0),
    CHECK (stack_count > 0)
);

CREATE INDEX character_buffs_character_idx ON player.character_buffs(character_id);

CREATE TABLE player.character_quests (
    character_id        uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    quest_definition_id bigint NOT NULL REFERENCES content.quest_definitions(id) ON DELETE RESTRICT,
    state               varchar(32) NOT NULL DEFAULT 'active',
    progress            jsonb NOT NULL DEFAULT '{}'::jsonb,
    started_at          timestamptz NOT NULL DEFAULT now(),
    completed_at        timestamptz,
    PRIMARY KEY (character_id, quest_definition_id)
);

-- -----------------------------------------------------------------------------
-- GAMEPLAY: durable audit/progression records; live combat remains in server memory
-- -----------------------------------------------------------------------------

CREATE TABLE gameplay.dungeon_runs (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    character_id        uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    dungeon_key         varchar(128) NOT NULL,
    started_at          timestamptz NOT NULL DEFAULT now(),
    finished_at         timestamptz,
    result              varchar(32),
    floor_reached       integer NOT NULL DEFAULT 0,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX dungeon_runs_character_idx ON gameplay.dungeon_runs(character_id, started_at DESC);

CREATE TABLE gameplay.combat_sessions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    dungeon_run_id      uuid REFERENCES gameplay.dungeon_runs(id) ON DELETE SET NULL,
    map_definition_id   bigint REFERENCES content.map_definitions(id) ON DELETE SET NULL,
    started_at          timestamptz NOT NULL DEFAULT now(),
    finished_at         timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE gameplay.combat_events (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    combat_session_id       uuid NOT NULL REFERENCES gameplay.combat_sessions(id) ON DELETE CASCADE,
    sequence_no             integer NOT NULL,
    occurred_at             timestamptz NOT NULL DEFAULT now(),
    event_type              varchar(64) NOT NULL,
    actor_character_id      uuid REFERENCES player.characters(id) ON DELETE SET NULL,
    actor_monster_instance  uuid,
    target_character_id     uuid REFERENCES player.characters(id) ON DELETE SET NULL,
    target_monster_instance uuid,
    magic_definition_id     bigint REFERENCES content.magic_definitions(id) ON DELETE SET NULL,
    item_definition_id      bigint REFERENCES content.item_definitions(id) ON DELETE SET NULL,
    amount                  numeric(30,4),
    element                 varchar(32),
    payload                 jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (combat_session_id, sequence_no)
);

CREATE INDEX combat_events_session_idx ON gameplay.combat_events(combat_session_id, sequence_no);
CREATE INDEX combat_events_magic_idx ON gameplay.combat_events(magic_definition_id)
    WHERE magic_definition_id IS NOT NULL;
CREATE INDEX combat_events_actor_character_idx ON gameplay.combat_events(actor_character_id, occurred_at DESC)
    WHERE actor_character_id IS NOT NULL;

CREATE TABLE gameplay.monster_kills (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id            uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    monster_definition_id   bigint NOT NULL REFERENCES content.monster_definitions(id) ON DELETE RESTRICT,
    combat_session_id       uuid REFERENCES gameplay.combat_sessions(id) ON DELETE SET NULL,
    killed_at               timestamptz NOT NULL DEFAULT now(),
    experience_awarded      numeric(30,0) NOT NULL DEFAULT 0,
    payload                 jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX monster_kills_character_idx ON gameplay.monster_kills(character_id, killed_at DESC);
CREATE INDEX monster_kills_monster_idx ON gameplay.monster_kills(monster_definition_id, killed_at DESC);

COMMIT;
