-- ORIGINS DATA FOUNDATION V1
-- Hybrid item authority:
--   Zircon = canonical/base item catalogue where available.
--   Crystal / Crystal-Monk = class-specific balance overlays (not duplicate items).

BEGIN;

-- Links one canonical ORIGINS item to any number of upstream item records.
-- This allows a Zircon base item to retain Crystal/Monk provenance without
-- creating duplicate inventory definitions.
CREATE TABLE content.item_source_links (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    source_system       varchar(32) NOT NULL,
    source_item_id      integer,
    source_name         varchar(160),
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    match_method        varchar(32) NOT NULL DEFAULT 'manual',
    match_confidence    numeric(5,4) NOT NULL DEFAULT 1,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (match_method IN ('id','name','shape','manual','importer')),
    CHECK (match_confidence >= 0 AND match_confidence <= 1)
);

CREATE UNIQUE INDEX item_source_links_source_uidx
    ON content.item_source_links(source_system, source_item_id)
    WHERE source_item_id IS NOT NULL;

CREATE INDEX item_source_links_item_idx
    ON content.item_source_links(item_definition_id);

-- Per-class requirements/equipment policy. NULL override values mean: inherit
-- the canonical values from content.item_definitions.
CREATE TABLE content.item_class_profiles (
    item_definition_id      bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    class_id                smallint NOT NULL REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    enabled                 boolean NOT NULL DEFAULT true,
    required_type_override  varchar(64),
    required_amount_override integer,
    item_effect_override    varchar(128),
    shape_override          integer,
    source_system           varchar(32),
    source_item_id          integer,
    source_repo             text,
    source_path             text,
    source_commit           varchar(64),
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (item_definition_id, class_id),
    CHECK (required_amount_override IS NULL OR required_amount_override >= 0)
);

CREATE INDEX item_class_profiles_class_idx
    ON content.item_class_profiles(class_id, enabled);

-- Per-class stat overlay. The effective item stat for a class is:
--   class override when present; otherwise content.item_stats base value.
-- `mode = replace` is the normal Crystal balance case; add/multiply are kept
-- for future ORIGINS tuning without cloning item definitions.
CREATE TABLE content.item_class_stats (
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    class_id            smallint NOT NULL REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    stat_code           varchar(64) NOT NULL,
    amount              numeric(18,6) NOT NULL,
    mode                varchar(16) NOT NULL DEFAULT 'replace',
    source_system       varchar(32) NOT NULL,
    source_item_id      integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (item_definition_id, class_id, stat_code),
    CHECK (mode IN ('replace','add','multiply'))
);

CREATE INDEX item_class_stats_class_idx
    ON content.item_class_stats(class_id, stat_code);

-- Explicit import policy kept in the database so tools and future server code
-- cannot silently switch source authority.
CREATE TABLE content.item_source_policy (
    class_id            smallint PRIMARY KEY REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    canonical_source    varchar(32) NOT NULL,
    stats_source        varchar(32) NOT NULL,
    fallback_source     varchar(32),
    notes               text,
    updated_at          timestamptz NOT NULL DEFAULT now()
);

INSERT INTO content.item_source_policy
    (class_id, canonical_source, stats_source, fallback_source, notes)
VALUES
    (1, 'zircon', 'zircon', 'crystal', 'Warrior: prefer Zircon item catalogue and stats.'),
    (2, 'zircon', 'zircon', 'crystal', 'Wizard: prefer Zircon item catalogue and stats.'),
    (3, 'zircon', 'zircon', 'crystal', 'Taoist: prefer Zircon item catalogue and stats.'),
    (4, 'zircon', 'crystal', 'zircon', 'Assassin: Zircon canonical item; Crystal stats overlay when matched.'),
    (5, 'zircon', 'crystal', NULL, 'Archer: Crystal supplies class-specific item requirements/stats; canonical item may be matched to Zircon or created when no Zircon equivalent exists.'),
    (6, 'zircon', 'crystal-monk', 'crystal', 'Monk: Crystal-Monk/Jev supplies class-specific item requirements/stats; canonical item may be matched to Zircon or created when no Zircon equivalent exists.');

-- Convenience view used by runtime/importer QA. One row per item/class/stat,
-- preferring the class-specific overlay and otherwise inheriting base stats.
CREATE VIEW content.effective_item_stats AS
SELECT
    i.id AS item_definition_id,
    c.id AS class_id,
    c.code AS class_code,
    base.stat_code,
    CASE
        WHEN overlay.mode = 'replace' THEN overlay.amount
        WHEN overlay.mode = 'add' THEN base.amount + overlay.amount
        WHEN overlay.mode = 'multiply' THEN base.amount * overlay.amount
        ELSE base.amount
    END AS amount,
    COALESCE(overlay.source_system, i.source_system, 'origins') AS effective_source
FROM content.item_definitions i
CROSS JOIN content.class_definitions c
JOIN content.item_stats base
  ON base.item_definition_id = i.id
LEFT JOIN content.item_class_stats overlay
  ON overlay.item_definition_id = i.id
 AND overlay.class_id = c.id
 AND overlay.stat_code = base.stat_code
UNION ALL
SELECT
    i.id,
    c.id,
    c.code,
    overlay.stat_code,
    overlay.amount,
    overlay.source_system
FROM content.item_definitions i
JOIN content.item_class_stats overlay
  ON overlay.item_definition_id = i.id
JOIN content.class_definitions c
  ON c.id = overlay.class_id
WHERE NOT EXISTS (
    SELECT 1
    FROM content.item_stats base
    WHERE base.item_definition_id = i.id
      AND base.stat_code = overlay.stat_code
);

COMMIT;
