-- ORIGINS DATA FOUNDATION V1
-- World/content systems required by Zircon-style gameplay.

BEGIN;

-- -----------------------------------------------------------------------------
-- Economy / currencies
-- -----------------------------------------------------------------------------
CREATE TABLE content.currency_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(128) NOT NULL UNIQUE,
    name                varchar(128) NOT NULL,
    abbreviation        varchar(32),
    currency_type       varchar(64),
    category            varchar(64),
    drop_item_id        bigint REFERENCES content.item_definitions(id) ON DELETE SET NULL,
    exchange_rate       numeric(20,6) NOT NULL DEFAULT 1,
    image_library       varchar(128),
    image_index         integer,
    source_system       varchar(32),
    source_numeric_id   integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (exchange_rate > 0)
);

CREATE TABLE player.character_currencies (
    character_id        uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    currency_id         bigint NOT NULL REFERENCES content.currency_definitions(id) ON DELETE RESTRICT,
    amount              numeric(30,0) NOT NULL DEFAULT 0,
    updated_at          timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (character_id, currency_id),
    CHECK (amount >= 0)
);

-- -----------------------------------------------------------------------------
-- Map regions / transitions / dungeons
-- -----------------------------------------------------------------------------
CREATE TABLE content.map_regions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_definition_id   bigint NOT NULL REFERENCES content.map_definitions(id) ON DELETE CASCADE,
    game_key            varchar(160) NOT NULL,
    description         varchar(200),
    region_type         varchar(32) NOT NULL DEFAULT 'area',
    x                   integer NOT NULL,
    y                   integer NOT NULL,
    width               integer NOT NULL DEFAULT 1,
    height              integer NOT NULL DEFAULT 1,
    is_safe_zone        boolean NOT NULL DEFAULT false,
    fight_mode          varchar(32),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (map_definition_id, game_key),
    CHECK (width > 0),
    CHECK (height > 0),
    CHECK (region_type IN ('area','connection','spawn','npc','spawn_connection','path','room','boss_room'))
);

CREATE INDEX map_regions_map_idx ON content.map_regions(map_definition_id, region_type);

CREATE TABLE content.map_connections (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_region_id          bigint NOT NULL REFERENCES content.map_regions(id) ON DELETE CASCADE,
    to_map_definition_id    bigint NOT NULL REFERENCES content.map_definitions(id) ON DELETE CASCADE,
    to_x                    integer NOT NULL,
    to_y                    integer NOT NULL,
    direction_hint          varchar(32),
    requires_clear          boolean NOT NULL DEFAULT false,
    locked                  boolean NOT NULL DEFAULT false,
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX map_connections_from_idx ON content.map_connections(from_region_id);
CREATE INDEX map_connections_to_idx ON content.map_connections(to_map_definition_id);

CREATE TABLE content.dungeon_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(128) NOT NULL UNIQUE,
    name                varchar(160) NOT NULL,
    description         text,
    spawn_multiplier    numeric(10,4) NOT NULL DEFAULT 1,
    min_level           integer,
    max_players         integer,
    mode                varchar(32) NOT NULL DEFAULT 'solo',
    source_system       varchar(32),
    source_numeric_id   integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (spawn_multiplier > 0),
    CHECK (min_level IS NULL OR min_level >= 0),
    CHECK (max_players IS NULL OR max_players > 0),
    CHECK (mode IN ('solo','group','guild','event'))
);

CREATE TABLE content.dungeon_maps (
    dungeon_definition_id bigint NOT NULL REFERENCES content.dungeon_definitions(id) ON DELETE CASCADE,
    map_definition_id     bigint NOT NULL REFERENCES content.map_definitions(id) ON DELETE CASCADE,
    floor                 integer NOT NULL DEFAULT 1,
    role                  varchar(32) NOT NULL DEFAULT 'floor',
    sort_order            integer NOT NULL DEFAULT 0,
    PRIMARY KEY (dungeon_definition_id, map_definition_id),
    CHECK (floor >= 0),
    CHECK (role IN ('entrance','lobby','floor','side_room','transition','hub','maze','boss_floor','king_room'))
);

-- -----------------------------------------------------------------------------
-- NPC / shops
-- -----------------------------------------------------------------------------
CREATE TABLE content.npc_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(160) NOT NULL UNIQUE,
    npc_name            varchar(160) NOT NULL,
    map_region_id       bigint REFERENCES content.map_regions(id) ON DELETE SET NULL,
    category            varchar(64),
    dialog_type         varchar(64),
    image_library       varchar(128),
    image_index         integer,
    face_library        varchar(128),
    face_index          integer,
    map_icon            varchar(64),
    entry_text_key      varchar(200),
    source_system       varchar(32),
    source_numeric_id   integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX npc_definitions_region_idx ON content.npc_definitions(map_region_id);

CREATE TABLE content.npc_shop_goods (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    npc_definition_id   bigint NOT NULL REFERENCES content.npc_definitions(id) ON DELETE CASCADE,
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE RESTRICT,
    currency_id         bigint REFERENCES content.currency_definitions(id) ON DELETE RESTRICT,
    price_override      numeric(30,0),
    rate                numeric(12,6) NOT NULL DEFAULT 1,
    stock_limit         bigint,
    sort_order          integer NOT NULL DEFAULT 0,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (npc_definition_id, item_definition_id, currency_id),
    CHECK (price_override IS NULL OR price_override >= 0),
    CHECK (rate > 0),
    CHECK (stock_limit IS NULL OR stock_limit >= 0)
);

-- -----------------------------------------------------------------------------
-- Quests: structure rather than hard-coded scripts
-- -----------------------------------------------------------------------------
ALTER TABLE content.quest_definitions
    ADD COLUMN quest_type varchar(32) NOT NULL DEFAULT 'general',
    ADD COLUMN accept_text text,
    ADD COLUMN progress_text text,
    ADD COLUMN completed_text text,
    ADD COLUMN archive_text text,
    ADD COLUMN start_npc_id bigint REFERENCES content.npc_definitions(id) ON DELETE SET NULL,
    ADD COLUMN finish_npc_id bigint REFERENCES content.npc_definitions(id) ON DELETE SET NULL,
    ADD CONSTRAINT quest_type_check CHECK (quest_type IN ('general','daily','repeatable','story','clan','event'));

CREATE TABLE content.quest_tasks (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_definition_id bigint NOT NULL REFERENCES content.quest_definitions(id) ON DELETE CASCADE,
    task_type           varchar(64) NOT NULL,
    amount              integer NOT NULL DEFAULT 1,
    item_definition_id  bigint REFERENCES content.item_definitions(id) ON DELETE RESTRICT,
    monster_definition_id bigint REFERENCES content.monster_definitions(id) ON DELETE RESTRICT,
    map_definition_id   bigint REFERENCES content.map_definitions(id) ON DELETE SET NULL,
    region_id           bigint REFERENCES content.map_regions(id) ON DELETE SET NULL,
    description         text,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (amount > 0)
);

CREATE INDEX quest_tasks_quest_idx ON content.quest_tasks(quest_definition_id);

CREATE TABLE content.quest_rewards (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quest_definition_id bigint NOT NULL REFERENCES content.quest_definitions(id) ON DELETE CASCADE,
    reward_type         varchar(32) NOT NULL,
    item_definition_id  bigint REFERENCES content.item_definitions(id) ON DELETE RESTRICT,
    currency_id         bigint REFERENCES content.currency_definitions(id) ON DELETE RESTRICT,
    amount              numeric(30,0) NOT NULL DEFAULT 1,
    class_id            smallint REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    choice              boolean NOT NULL DEFAULT false,
    bound               boolean NOT NULL DEFAULT false,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (amount >= 0),
    CHECK (reward_type IN ('item','currency','experience','gold','magic','custom'))
);

CREATE INDEX quest_rewards_quest_idx ON content.quest_rewards(quest_definition_id);

-- -----------------------------------------------------------------------------
-- Monster spell/skill loadouts and player pets/summons
-- -----------------------------------------------------------------------------
CREATE TABLE content.monster_magics (
    monster_definition_id bigint NOT NULL REFERENCES content.monster_definitions(id) ON DELETE CASCADE,
    magic_definition_id   bigint NOT NULL REFERENCES content.magic_definitions(id) ON DELETE RESTRICT,
    priority              integer NOT NULL DEFAULT 0,
    chance                numeric(8,6) NOT NULL DEFAULT 1,
    min_range             integer NOT NULL DEFAULT 0,
    max_range             integer,
    cooldown_ms           integer,
    metadata              jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (monster_definition_id, magic_definition_id),
    CHECK (chance >= 0 AND chance <= 1),
    CHECK (min_range >= 0),
    CHECK (max_range IS NULL OR max_range >= min_range),
    CHECK (cooldown_ms IS NULL OR cooldown_ms >= 0)
);

CREATE TABLE content.summon_definitions (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key                varchar(160) NOT NULL UNIQUE,
    owner_class_id          smallint REFERENCES content.class_definitions(id) ON DELETE SET NULL,
    source_magic_id         bigint REFERENCES content.magic_definitions(id) ON DELETE SET NULL,
    monster_definition_id   bigint NOT NULL REFERENCES content.monster_definitions(id) ON DELETE RESTRICT,
    base_level              integer NOT NULL DEFAULT 1,
    max_level               integer,
    duration_ms             bigint,
    persist_between_sessions boolean NOT NULL DEFAULT false,
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (base_level >= 0),
    CHECK (max_level IS NULL OR max_level >= base_level),
    CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE TABLE player.character_pets (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    character_id        uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    summon_definition_id bigint NOT NULL REFERENCES content.summon_definitions(id) ON DELETE RESTRICT,
    pet_name            varchar(64),
    level               integer NOT NULL DEFAULT 1,
    experience          numeric(30,0) NOT NULL DEFAULT 0,
    hp                  integer,
    loyalty             integer,
    active              boolean NOT NULL DEFAULT false,
    expires_at          timestamptz,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (level >= 0),
    CHECK (experience >= 0),
    CHECK (hp IS NULL OR hp >= 0)
);

CREATE INDEX character_pets_character_idx ON player.character_pets(character_id, active);

COMMIT;
