-- ORIGINS DATA FOUNDATION V1
-- Class restrictions apply ONLY to equipment.
-- Any class may own, loot, store, trade, sell or list an item unless a separate
-- trade/bind rule explicitly forbids it.

BEGIN;

CREATE SCHEMA IF NOT EXISTS economy;

-- Optional item-level transfer policy, independent from class equipability.
ALTER TABLE content.item_definitions
    ADD COLUMN can_trade boolean NOT NULL DEFAULT true,
    ADD COLUMN can_sell boolean NOT NULL DEFAULT true,
    ADD COLUMN can_store boolean NOT NULL DEFAULT true,
    ADD COLUMN can_auction boolean NOT NULL DEFAULT true;

-- Active auction/consignment listing. The item remains a unique UserItem and is
-- held in market escrow by having no inventory/equipment/storage slot while the
-- listing is active. Ownership changes only when the sale completes.
CREATE TABLE economy.market_listings (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    seller_character_id uuid NOT NULL REFERENCES player.characters(id) ON DELETE CASCADE,
    item_instance_id    uuid NOT NULL REFERENCES player.item_instances(id) ON DELETE RESTRICT,
    currency_id         bigint REFERENCES content.currency_definitions(id) ON DELETE RESTRICT,
    unit_price          numeric(30,0) NOT NULL,
    quantity            bigint NOT NULL DEFAULT 1,
    status              varchar(16) NOT NULL DEFAULT 'active',
    listed_at           timestamptz NOT NULL DEFAULT now(),
    expires_at          timestamptz,
    completed_at        timestamptz,
    buyer_character_id  uuid REFERENCES player.characters(id) ON DELETE SET NULL,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (unit_price >= 0),
    CHECK (quantity > 0),
    CHECK (status IN ('active','sold','cancelled','expired'))
);

CREATE UNIQUE INDEX market_listings_active_item_uidx
    ON economy.market_listings(item_instance_id)
    WHERE status = 'active';

CREATE INDEX market_listings_active_idx
    ON economy.market_listings(status, listed_at DESC);

CREATE INDEX market_listings_seller_idx
    ON economy.market_listings(seller_character_id, listed_at DESC);

CREATE TABLE economy.market_transactions (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    listing_id          uuid NOT NULL REFERENCES economy.market_listings(id) ON DELETE RESTRICT,
    seller_character_id uuid NOT NULL REFERENCES player.characters(id) ON DELETE RESTRICT,
    buyer_character_id  uuid NOT NULL REFERENCES player.characters(id) ON DELETE RESTRICT,
    item_instance_id    uuid NOT NULL REFERENCES player.item_instances(id) ON DELETE RESTRICT,
    currency_id         bigint REFERENCES content.currency_definitions(id) ON DELETE RESTRICT,
    total_price         numeric(30,0) NOT NULL,
    quantity            bigint NOT NULL,
    completed_at        timestamptz NOT NULL DEFAULT now(),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (total_price >= 0),
    CHECK (quantity > 0)
);

-- Generic economy audit also covers NPC sale, direct trade and auction.
CREATE TABLE economy.item_transactions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_instance_id    uuid REFERENCES player.item_instances(id) ON DELETE SET NULL,
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE RESTRICT,
    transaction_type    varchar(32) NOT NULL,
    from_character_id   uuid REFERENCES player.characters(id) ON DELETE SET NULL,
    to_character_id     uuid REFERENCES player.characters(id) ON DELETE SET NULL,
    npc_definition_id   bigint REFERENCES content.npc_definitions(id) ON DELETE SET NULL,
    quantity            bigint NOT NULL DEFAULT 1,
    amount              numeric(30,0),
    currency_id         bigint REFERENCES content.currency_definitions(id) ON DELETE SET NULL,
    occurred_at         timestamptz NOT NULL DEFAULT now(),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (quantity > 0),
    CHECK (amount IS NULL OR amount >= 0),
    CHECK (transaction_type IN ('loot','npc_buy','npc_sell','direct_trade','auction_list','auction_sale','auction_cancel','mail','gm','system'))
);

-- Explicit helper used by server/UI. Note that this does NOT inspect class.
CREATE FUNCTION content.can_character_possess_item(p_item_definition_id bigint, p_mode varchar)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
    SELECT CASE lower(p_mode)
        WHEN 'inventory' THEN true
        WHEN 'loot' THEN true
        WHEN 'storage' THEN i.can_store
        WHEN 'trade' THEN i.can_trade
        WHEN 'sell' THEN i.can_sell
        WHEN 'auction' THEN i.can_auction AND i.can_trade
        ELSE false
    END
    FROM content.item_definitions i
    WHERE i.id = p_item_definition_id;
$$;

-- Listing validation is ownership/transfer based, never class based.
CREATE FUNCTION economy.validate_market_listing()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    v_owner uuid;
    v_item_definition_id bigint;
    v_count bigint;
    v_bound boolean;
BEGIN
    IF NEW.status <> 'active' THEN
        RETURN NEW;
    END IF;

    SELECT owner_character_id, item_definition_id, count, bound
      INTO v_owner, v_item_definition_id, v_count, v_bound
      FROM player.item_instances
     WHERE id = NEW.item_instance_id;

    IF v_item_definition_id IS NULL THEN
        RAISE EXCEPTION 'Unknown market item instance %', NEW.item_instance_id;
    END IF;

    IF v_owner IS DISTINCT FROM NEW.seller_character_id THEN
        RAISE EXCEPTION 'Seller % does not own item instance %', NEW.seller_character_id, NEW.item_instance_id;
    END IF;

    IF v_bound THEN
        RAISE EXCEPTION 'Bound item instance % cannot be auctioned', NEW.item_instance_id;
    END IF;

    IF NOT content.can_character_possess_item(v_item_definition_id, 'auction') THEN
        RAISE EXCEPTION 'Item definition % cannot be auctioned', v_item_definition_id;
    END IF;

    IF NEW.quantity > v_count THEN
        RAISE EXCEPTION 'Auction quantity % exceeds item count %', NEW.quantity, v_count;
    END IF;

    IF EXISTS (
        SELECT 1 FROM player.character_item_slots s
        WHERE s.item_instance_id = NEW.item_instance_id
    ) THEN
        RAISE EXCEPTION 'Item instance % must leave inventory/storage/equipment before market listing', NEW.item_instance_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER market_listing_integrity_trigger
BEFORE INSERT OR UPDATE ON economy.market_listings
FOR EACH ROW
EXECUTE FUNCTION economy.validate_market_listing();

-- Market escrow rule: an actively listed item cannot simultaneously sit in a
-- character slot. This is NOT a class rule; it only prevents duplication.
CREATE FUNCTION player.validate_item_not_in_market_escrow()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM economy.market_listings l
        WHERE l.item_instance_id = NEW.item_instance_id
          AND l.status = 'active'
    ) THEN
        RAISE EXCEPTION 'Item instance % is in active market escrow', NEW.item_instance_id;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER character_item_market_escrow_trigger
BEFORE INSERT OR UPDATE ON player.character_item_slots
FOR EACH ROW
EXECUTE FUNCTION player.validate_item_not_in_market_escrow();

COMMIT;
