-- ORIGINS DATA FOUNDATION V1
-- Equipment identity/progression is separated from runtime behaviour.
-- Crystal / Crystal-Monk may supply names, required levels and class balance.
-- Zircon supplies reusable ItemInfo-style runtime semantics (effects, buff icon,
-- durability/trade flags, set linkage and handler metadata).

BEGIN;

-- -----------------------------------------------------------------------------
-- Reusable Zircon-style runtime profiles.
-- Multiple ORIGINS items may reuse one profile while keeping different names,
-- class restrictions and stats.
-- -----------------------------------------------------------------------------
CREATE TABLE content.item_runtime_profiles (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key                varchar(160) NOT NULL UNIQUE,
    runtime_source          varchar(32) NOT NULL DEFAULT 'zircon',
    source_item_id          integer,
    source_item_name        varchar(160),
    item_type               varchar(64) NOT NULL,
    item_effect             varchar(128),
    exterior_effect         varchar(128),
    handler_key             varchar(160),
    script_key              varchar(200),
    buff_icon_library       varchar(128),
    buff_icon_index         integer,
    durability_policy       varchar(32) NOT NULL DEFAULT 'normal',
    can_repair              boolean NOT NULL DEFAULT true,
    can_sell                boolean NOT NULL DEFAULT true,
    can_store               boolean NOT NULL DEFAULT true,
    can_trade               boolean NOT NULL DEFAULT true,
    can_drop                boolean NOT NULL DEFAULT true,
    can_death_drop          boolean NOT NULL DEFAULT true,
    can_auction             boolean NOT NULL DEFAULT true,
    source_repo             text,
    source_path             text,
    source_commit           varchar(64),
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (runtime_source IN ('zircon','origins')),
    CHECK (durability_policy IN ('normal','none','consumable','permanent'))
);

CREATE UNIQUE INDEX item_runtime_profiles_zircon_source_uidx
    ON content.item_runtime_profiles(source_item_id)
    WHERE runtime_source='zircon' AND source_item_id IS NOT NULL;

-- Every concrete ORIGINS item can point to one reusable runtime profile.
ALTER TABLE content.item_definitions
    ADD COLUMN runtime_profile_id bigint REFERENCES content.item_runtime_profiles(id) ON DELETE SET NULL;

CREATE INDEX item_definitions_runtime_profile_idx
    ON content.item_definitions(runtime_profile_id)
    WHERE runtime_profile_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- Equipment progression by class.
-- This is the table used to answer: "what gear exists for this class and up to
-- what level/tier?" without depending on images.
-- -----------------------------------------------------------------------------
CREATE TABLE content.equipment_progression (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id                smallint NOT NULL REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    slot_code               varchar(32) NOT NULL,
    tier_order              integer NOT NULL,
    progression_name        varchar(160) NOT NULL,
    item_definition_id      bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    required_type           varchar(64) NOT NULL DEFAULT 'Level',
    required_amount         integer NOT NULL DEFAULT 0,
    source_system           varchar(32) NOT NULL,
    source_item_id          integer,
    source_item_name        varchar(160),
    source_repo             text,
    source_path             text,
    source_commit           varchar(64),
    runtime_source          varchar(32) NOT NULL DEFAULT 'zircon',
    notes                   text,
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (class_id, slot_code, tier_order),
    UNIQUE (class_id, item_definition_id),
    CHECK (tier_order >= 0),
    CHECK (required_amount >= 0),
    CHECK (runtime_source IN ('zircon','origins')),
    CHECK (slot_code IN (
        'weapon','armour','helmet','torch','necklace','bracelet_left','bracelet_right',
        'ring_left','ring_right','shoes','poison','amulet','flower','horse_armour',
        'emblem','shield','costume','hook','float','bait','finder','reel'
    ))
);

CREATE INDEX equipment_progression_class_level_idx
    ON content.equipment_progression(class_id, required_amount, tier_order);

CREATE INDEX equipment_progression_slot_idx
    ON content.equipment_progression(slot_code, required_amount, tier_order);

-- Report view: maximum configured equipment level/tier per class and slot.
CREATE VIEW content.equipment_progression_coverage AS
SELECT
    c.id AS class_id,
    c.code AS class_code,
    p.slot_code,
    count(*) AS item_count,
    max(p.required_amount) FILTER (WHERE lower(p.required_type)='level') AS max_required_level,
    max(p.tier_order) AS max_tier
FROM content.class_definitions c
LEFT JOIN content.equipment_progression p ON p.class_id=c.id
GROUP BY c.id,c.code,p.slot_code;

-- Overall class report useful for CI/import reports.
CREATE VIEW content.equipment_class_coverage AS
SELECT
    c.id AS class_id,
    c.code AS class_code,
    count(p.id) AS progression_items,
    count(DISTINCT p.slot_code) AS covered_slots,
    max(p.required_amount) FILTER (WHERE lower(p.required_type)='level') AS max_required_level,
    max(p.tier_order) AS max_tier
FROM content.class_definitions c
LEFT JOIN content.equipment_progression p ON p.class_id=c.id
GROUP BY c.id,c.code;

-- -----------------------------------------------------------------------------
-- Zircon SetInfo / SetInfoStat equivalent.
-- -----------------------------------------------------------------------------
CREATE TABLE content.item_set_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(160) NOT NULL UNIQUE,
    set_name            varchar(160) NOT NULL,
    source_system       varchar(32) NOT NULL DEFAULT 'zircon',
    source_set_id       integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE content.item_set_members (
    item_set_id         bigint NOT NULL REFERENCES content.item_set_definitions(id) ON DELETE CASCADE,
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    PRIMARY KEY (item_set_id,item_definition_id)
);

CREATE TABLE content.item_set_bonuses (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_set_id         bigint NOT NULL REFERENCES content.item_set_definitions(id) ON DELETE CASCADE,
    pieces_required     integer NOT NULL,
    class_id            smallint REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    stat_code           varchar(64),
    amount              numeric(18,6),
    buff_definition_id  bigint REFERENCES content.buff_definitions(id) ON DELETE SET NULL,
    effect_key          varchar(160),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (pieces_required > 0),
    CHECK (stat_code IS NOT NULL OR buff_definition_id IS NOT NULL OR effect_key IS NOT NULL)
);

CREATE INDEX item_set_bonuses_set_idx
    ON content.item_set_bonuses(item_set_id,pieces_required);

-- -----------------------------------------------------------------------------
-- Explicit item -> buff/effect relationships.
-- ItemInfo.BuffIcon remains available on item_definitions/runtime profile, while
-- these rows describe actual gameplay buffs so icons and effects are not mixed.
-- -----------------------------------------------------------------------------
CREATE TABLE content.item_buff_effects (
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    buff_definition_id  bigint NOT NULL REFERENCES content.buff_definitions(id) ON DELETE CASCADE,
    trigger_type        varchar(32) NOT NULL DEFAULT 'equipped',
    stack_mode          varchar(32) NOT NULL DEFAULT 'replace',
    magnitude           numeric(18,6),
    duration_ms         bigint,
    source_system       varchar(32) NOT NULL DEFAULT 'zircon',
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (item_definition_id,buff_definition_id,trigger_type),
    CHECK (trigger_type IN ('equipped','use','hit','struck','kill','low_hp','passive')),
    CHECK (stack_mode IN ('replace','stack','refresh','ignore')),
    CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

-- Resolved runtime item contract used by the server. Identity/balance stays on
-- item_definitions; behaviour defaults come from the linked Zircon profile.
CREATE VIEW content.resolved_item_runtime AS
SELECT
    i.id AS item_definition_id,
    i.game_key,
    i.item_name,
    i.item_type,
    COALESCE(r.item_effect,i.item_effect) AS item_effect,
    COALESCE(r.exterior_effect,i.exterior_effect) AS exterior_effect,
    COALESCE(r.buff_icon_library,i.image_library) AS buff_icon_library,
    COALESCE(r.buff_icon_index,i.buff_icon) AS buff_icon_index,
    r.handler_key,
    r.script_key,
    COALESCE(r.can_repair,i.can_repair) AS can_repair,
    COALESCE(r.can_sell,i.can_sell) AS can_sell,
    COALESCE(r.can_store,i.can_store) AS can_store,
    COALESCE(r.can_trade,i.can_trade) AS can_trade,
    COALESCE(r.can_drop,i.can_drop) AS can_drop,
    COALESCE(r.can_death_drop,i.can_death_drop) AS can_death_drop,
    COALESCE(r.can_auction,i.can_auction) AS can_auction,
    r.runtime_source,
    r.source_item_id AS runtime_source_item_id,
    r.source_item_name AS runtime_source_item_name
FROM content.item_definitions i
LEFT JOIN content.item_runtime_profiles r ON r.id=i.runtime_profile_id;

COMMIT;
