-- ORIGINS DATA FOUNDATION V1
-- Crystal class equipment enters ORIGINS as real canonical items with original
-- names, requirements and FLAT stats. Zircon supplies the item/runtime model:
-- inventory, equipment, repair, store/trade/auction, ItemEffect/BuffIcon, sets,
-- handlers and future special effects. No Crystal stat is invented here.

BEGIN;

-- Runtime hooks live directly on the canonical item. Crystal equipment does not
-- need to masquerade as or be merged into a different Zircon item.
ALTER TABLE content.item_definitions
    ADD COLUMN runtime_source varchar(32) NOT NULL DEFAULT 'zircon',
    ADD COLUMN runtime_handler_key varchar(160),
    ADD COLUMN runtime_script_key varchar(200),
    ADD CONSTRAINT item_runtime_source_check CHECK (runtime_source IN ('zircon','origins'));

-- Crystal adds Belt as an equipment family that Zircon's original slot enum did
-- not expose. Crystal Boots use the existing ORIGINS/Zircon `shoes` slot.
INSERT INTO content.equipment_slot_definitions (id,slot_code,display_name,equip_group)
VALUES (22,'belt','Belt','character')
ON CONFLICT (id) DO NOTHING;

-- Keep the equip allow-list aware of Belt.
ALTER TABLE content.item_equip_slots DROP CONSTRAINT item_equip_slots_slot_code_check;
ALTER TABLE content.item_equip_slots
    ADD CONSTRAINT item_equip_slots_slot_code_check CHECK (slot_code IN (
        'weapon','armour','helmet','torch','necklace','bracelet_left','bracelet_right',
        'ring_left','ring_right','shoes','belt','poison','amulet','flower','horse_armour',
        'emblem','shield','costume','hook','float','bait','finder','reel'
    ));

-- -----------------------------------------------------------------------------
-- Equipment progression by class.
-- One row is one real Crystal/Crystal-Monk equipment item in the progression.
-- `required_type` is preserved because some Mir items require a stat rather than
-- a player level. `max_required_level` reports only genuine Level requirements.
-- -----------------------------------------------------------------------------
CREATE TABLE content.equipment_progression (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id                smallint NOT NULL REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    equipment_family        varchar(32) NOT NULL,
    tier_order              integer NOT NULL,
    item_definition_id      bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    original_name           varchar(160) NOT NULL,
    required_type           varchar(64) NOT NULL,
    required_amount         integer NOT NULL DEFAULT 0,
    source_system           varchar(32) NOT NULL,
    source_item_id          integer,
    source_set_id           integer,
    source_repo             text,
    source_path             text,
    source_commit           varchar(64),
    metadata                jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (class_id,item_definition_id),
    CHECK (tier_order >= 0),
    CHECK (required_amount >= 0),
    CHECK (equipment_family IN (
        'weapon','armour','helmet','necklace','bracelet','ring','amulet','belt','boots','torch'
    ))
);

CREATE INDEX equipment_progression_class_level_idx
    ON content.equipment_progression(class_id,required_amount,tier_order);
CREATE INDEX equipment_progression_family_idx
    ON content.equipment_progression(equipment_family,required_amount,tier_order);

CREATE VIEW content.equipment_progression_coverage AS
SELECT
    c.id AS class_id,
    c.code AS class_code,
    p.equipment_family,
    count(p.id) AS item_count,
    max(p.required_amount) FILTER (WHERE lower(p.required_type)='level') AS max_required_level,
    max(p.tier_order) AS max_tier
FROM content.class_definitions c
LEFT JOIN content.equipment_progression p ON p.class_id=c.id
GROUP BY c.id,c.code,p.equipment_family;

CREATE VIEW content.equipment_class_coverage AS
SELECT
    c.id AS class_id,
    c.code AS class_code,
    count(p.id) AS progression_items,
    count(DISTINCT p.equipment_family) AS covered_families,
    max(p.required_amount) FILTER (WHERE lower(p.required_type)='level') AS max_required_level,
    max(p.tier_order) AS max_tier
FROM content.class_definitions c
LEFT JOIN content.equipment_progression p ON p.class_id=c.id
GROUP BY c.id,c.code;

-- Source policy is explicit: class equipment progression comes from Crystal;
-- Monk comes from Crystal-Monk when source data is available. Generic/non-class
-- items may still come from Zircon.
CREATE TABLE content.equipment_source_policy (
    class_id                smallint PRIMARY KEY REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    progression_source      varchar(32) NOT NULL,
    generic_item_source     varchar(32) NOT NULL DEFAULT 'zircon',
    stats_mode              varchar(16) NOT NULL DEFAULT 'flat',
    keep_original_names     boolean NOT NULL DEFAULT true,
    notes                   text,
    CHECK (stats_mode='flat')
);

INSERT INTO content.equipment_source_policy
    (class_id,progression_source,generic_item_source,stats_mode,keep_original_names,notes)
VALUES
    (1,'crystal','zircon','flat',true,'Warrior Crystal class equipment; generic items remain Zircon-compatible.'),
    (2,'crystal','zircon','flat',true,'Wizard Crystal class equipment; generic items remain Zircon-compatible.'),
    (3,'crystal','zircon','flat',true,'Taoist Crystal class equipment; generic items remain Zircon-compatible.'),
    (4,'crystal','zircon','flat',true,'Assassin Crystal class equipment with original flat stats.'),
    (5,'crystal','zircon','flat',true,'Archer Crystal class equipment with original DC/MC flat stats.'),
    (6,'crystal-monk','zircon','flat',true,'Monk Crystal-Monk equipment with original DC/SC flat stats when source DB is available.');

-- -----------------------------------------------------------------------------
-- Zircon SetInfo / SetInfoStat equivalent. Imported Crystal ItemSet membership is
-- stored here; future ORIGINS sets use the same tables.
-- -----------------------------------------------------------------------------
CREATE TABLE content.item_set_definitions (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_key            varchar(160) NOT NULL UNIQUE,
    set_name            varchar(160) NOT NULL,
    class_id            smallint REFERENCES content.class_definitions(id) ON DELETE SET NULL,
    source_system       varchar(32) NOT NULL,
    source_set_id       integer,
    source_repo         text,
    source_path         text,
    source_commit       varchar(64),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE content.item_set_members (
    item_set_id         bigint NOT NULL REFERENCES content.item_set_definitions(id) ON DELETE CASCADE,
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    PRIMARY KEY (item_set_id,item_definition_id)
);

-- Future set bonuses are supported but no bonus is fabricated during Crystal
-- import. Flat item stats remain exactly as stored in source.
CREATE TABLE content.item_set_bonuses (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_set_id         bigint NOT NULL REFERENCES content.item_set_definitions(id) ON DELETE CASCADE,
    pieces_required     integer NOT NULL,
    class_id            smallint REFERENCES content.class_definitions(id) ON DELETE CASCADE,
    stat_code           varchar(64),
    amount              numeric(18,6),
    buff_definition_id  bigint REFERENCES content.buff_definitions(id) ON DELETE SET NULL,
    effect_key          varchar(160),
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (pieces_required > 0),
    CHECK (stat_code IS NOT NULL OR buff_definition_id IS NOT NULL OR effect_key IS NOT NULL)
);
CREATE INDEX item_set_bonuses_set_idx ON content.item_set_bonuses(item_set_id,pieces_required);

-- Item-triggered buffs/effects use Zircon-style runtime logic. Empty at import
-- unless the source explicitly defines an effect; later ORIGINS items can reuse it.
CREATE TABLE content.item_buff_effects (
    item_definition_id  bigint NOT NULL REFERENCES content.item_definitions(id) ON DELETE CASCADE,
    buff_definition_id  bigint NOT NULL REFERENCES content.buff_definitions(id) ON DELETE CASCADE,
    trigger_type        varchar(32) NOT NULL DEFAULT 'equipped',
    stack_mode          varchar(32) NOT NULL DEFAULT 'replace',
    magnitude           numeric(18,6),
    duration_ms         bigint,
    source_system       varchar(32) NOT NULL DEFAULT 'zircon',
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (item_definition_id,buff_definition_id,trigger_type),
    CHECK (trigger_type IN ('equipped','use','hit','struck','kill','low_hp','passive')),
    CHECK (stack_mode IN ('replace','stack','refresh','ignore')),
    CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

COMMIT;
